sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull debian:stable-slim

script:
  - docker version
  - docker build --no-cache --tag lltest/steamcmd:linux --tag lacledeslan/steamcmd:linux --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT=$(TRAVIS_COMMIT) ./linux
  - docker run -it --rm lltest/steamcmd:linux ./ll-tests/steamcmd.sh

notifications:
  slack:
    secure: OJtr+r4fCthl/1xAycplV9KE3v4ks3MfyofVXx0PzsFRw5HlxmHXj5rC+LVrKqw3xYUNoT6ss8mcaMhJ2fY0K1ykRKcn6BCoOp028O1DU7Wha+cI6Oy5WHxVdK4Bjht88TFF8TE7p69kvh+uvGjYn112IM7d5dFyXmLCRFKhIeI5NpEp2d3FpXKVjgYEnv3bC22WD+ztk7oXO0ZYWzlk2UwvqYCNE0lnPuppQAcTM2ClO3JMgtf5Ypd+FsB/OAd/znN6X/3JixuhcVtG2CupGFtMllqwWqWGPyDd4dt/jXWFp+ifum9/17pfg+Dy1N6+T7YC94onhBzh2QyDwNRaeO/ZO5KjOIjMzeJXzdbDeDSop+e714UKfXmzSKbrlrjYvCsd3UC6YF4A/E8D08Hrk3XFosecMHUnSP+1nLtJKWJLf5QR8wgB7X9myxIpa7NsmnJSjxN4xMkK9TxP+l1NVErBCpmNtEb9mNsENzCswPuNQm1qNYZTazDZqj1F1+axNaMobPCMFYh0u0b6IOc1JesXi3uD2+3SPaZKQdYh8OEnS3Gs7/o5RVYsLtx16cYM80V8YTXksuFNCoKND0N89xO1YAI2C3MKlEAQ75GI5z5FnaBPGN+CBSUMEu55YbbF+K9o/HPjMi7VycN+/iCqdxFiEhA5BGZfPvhCz7/7VkY=

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS";
deploy:
  provider: script
  script: docker push lacledeslan/steamcmd:linux
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/steamcmd/$MICROBADGER_TOKEN

