# This is a basic workflow to help you get started with Actions

name: linux/amd64

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 12 * * WED'
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Pull Latest Linux Base Image
        run: docker pull debian:stable-slim
      - name: Build Linux Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./linux.Dockerfile
          tags: |
            lacledeslan/steamcmd:latest
            lacledeslan/steamcmd:linux
            ghcr.io/lacledeslan/steamcmd:latest
            ghcr.io/lacledeslan/steamcmd:linux
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            SOURCE_COMMIT=${{ github.sha }}
          no-cache: true
      - name: Test Linux Image
        run: docker run --rm lacledeslan/steamcmd:latest /app/ll-tests/steamcmd.sh
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.LLCONTAINERS_USERNAME }}
          password: ${{ secrets.LLCONTAINERS_TOKEN }}
      - name: Update Docker HUB Description
        if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lacledeslan/steamcmd
          short-description: SteamCMD in Docker, for use as a builder image
          readme-filepath: ./README.md
      - name: Push to Docker HUB
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push lacledeslan/steamcmd:latest
          docker push lacledeslan/steamcmd:linux
      - name: Push to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ghcr.io/LacledesLAN/steamcmd:latest
          docker push ghcr.io/LacledesLAN/steamcmd:linux
