# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 12 * * WED'
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        name: Checkout 
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
         name: Pull Latest Linux Base Image
         run: docker pull debian:stable-slim
      -
        name: Build Linux Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./linux.Dockerfile
          tags: |
            lacledeslan/steamcmd:latest
            lacledeslan/steamcmd:linux
          build-args: |
            BUILDNODE=GitHub Actions
            SOURCE_COMMIT=$GITHUB_SHA
          no-cache: true
      -
          name: Test Linux Image
          run: docker run --rm lacledeslan/steamcmd:latest /app/ll-tests/steamcmd.sh
      -
         name: Push Linux Image to Docker HUB
         run: |
           docker push lacledeslan/steamcmd:latest
           docker push lacledeslan/steamcmd:linux
