name: Update Docker Hub Description

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Docker HUB Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: lacledeslan/steamcmd
          short-description: SteamCMD in Docker, for use as a builder image
          readme-filepath: ./README.md
